spring.application.name=FurnitureStore

# postgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/furniture
spring.datasource.username=furniture
spring.datasource.password=furniture
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false

# disable H2
spring.h2.console.enabled=false

# disable dev import
app.import-products-on-startup=false

# security, definitely not secure
spring.security.user.name=user
spring.security.user.password=1234